version: "3"
services:
  chatbot:
    build: ./python
    volumes:
      - ./python/src:/app
    environment:
    command: tail -f /dev/null
    depends_on:
      - redis
  redis:
    build: ./redis
    # volumes:
    #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # command: [ "/usr/local/etc/redis/redis.conf" ]
    ports:
      - 6379:6379
