apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot-container
          image: eddie0228/chatbot:latest
          imagePullPolicy: Always
          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: ACCESS_TOKEN
            - name: HOST
              value: "redis-service.default"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: REDIS_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: OPENAI_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: YOUTUBE_API_KEY
            - name: REDISPORT
              value: "6379"
